import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >        <nav className="navbar-container shadow-lg p-3 mb-5 bg-white rounded">

          <div className="logo-container">
            <img src={logo} className="profile-image" alt="Logo" />
          </div>

          <div className="bars" onClick={() => OpenCloseMenu()}>
            <div className="bar"></div>
            <div className="bar"></div>
            <div className="bar"></div>
          </div>

          <ul className={`nav-items ${isOpen ? "active" : ""}`}>
            <li className="nav-link" ><Link to="/" onClick={() => { OpenCloseMenu(); scrollToUp() }}>Home</Link></li>
            <li className="nav-link"><Link to="/product" onClick={() => { OpenCloseMenu(); scrollToUp() }}>Product</Link></li>
            <li className="nav-link"><Link to="/contact" onClick={() => { OpenCloseMenu(); scrollToUp() }}>Contact</Link></li>
            <li className="nav-link"><Link to="/about" onClick={() => { OpenCloseMenu(); scrollToUp() }}>About</Link></li>

            <div className="login-register">
              <a href="#" className="button">Login</a>
            </div>
            <div class="social_follow" >
              <ul className="ulSosal" >
                <li title="facebook" className="liSosal"><a href="#" target="_blank"><ImFacebook className="Icon facebook" /><span className="facebook spanSoshal">Facebook</span></a>
                </li>
                <li title="whatsapp" className="liSosal"><a href="https://api.whatsapp.com/send/?phone=%2B962781021110&text&type=phone_number&app_absent=0" target="_blank"><AiOutlineWhatsApp className="Icon whatsapp" /><span className="whatsapp spanSoshal">whatsapp</span></a>
                </li>
                <li title="instagram" className="liSosal"><a href="https://www.instagram.com/iksaShop/" target="_blank"><AiOutlineInstagram className="Icon instagram-gradient" /><span className="instagram-gradient spanSoshal">instagram</span></a>
                </li>
              </ul>
            </div>
          </ul>

        </nav>
        {children}
        <div style={{ backgroundColor: "black", color: "#fff" }}>footer</div>
      </body>
    </html>
  );
}
