import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import Header from "./components/includs/Header";
import Footers from "./components/includs/Footers"; import "./assets/css/bootstrap-css-floder/bootstrap.min.css";

import "./assets/css/us.css";

import "./assets/css/header.css";
import "./assets/css/footer.css";
import "./assets/css/card.css";


import "./assets/css/slider.css";


import "./assets/css/style.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          {children}</main>
        <Footers />
      </body>
    </html>
  );
}
