import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { CartProvider } from "./CartContext";




export const metadata: Metadata = {
  title: "Next Architecture Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "Arial , sans-serif", padding: 20 }}>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
